name: "Hello rtl_433 ad"
description: "First rtl_433 ad"
version: "0.0.1"
slug: "hello_rtl_433_ad" 
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application

    
    
options:
    command_line: "-d"
    forced_ids : ""
schema:
    command_line: str
    forced_ids: str?

